# Generated by Django 3.1.2 on 2020-11-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField(unique=True)),
                ('finished', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('cmd', models.TextField()),
                ('recipient', models.TextField()),
                ('response', models.TextField()),
                ('cmd_finished', models.DateTimeField(blank=True, null=True)),
                ('resp_finished', models.DateTimeField(blank=True, null=True)),
                ('downfile', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command', to='api.downfile')),
                ('upfile', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command', to='api.upfile')),
            ],
        ),
    ]
